import { expect, test } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

test('theme switches from the header and persists across routes, reloads and tabs', async ({ page, context }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => {
    if (message.type() === 'error') errors.push(message.text())
  })
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('.hero-visual img:visible')).toHaveAttribute('src', /acoffee-cinematic\.png/)
  const toggle = page.getByRole('button', { name: 'تغییر به تم روشن' })
  await expect(toggle).toBeInViewport()
  await toggle.click()
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(246, 241, 232)')
  await expect(page.locator('.hero-visual img:visible')).toHaveAttribute('src', /acoffee\.jpg/)
  await expect(page.locator('.product-card img:visible').first()).toHaveAttribute('src', /acoffee\.jpg/)
  await expect(page.getByRole('button', { name: 'تغییر به تم تیره' })).toBeVisible()
  await mkdir('artifacts/ui', { recursive: true })
  await page.screenshot({ path: `artifacts/ui/theme-switch-light-${testInfo.project.name}.png` })
  await page.locator('.announcement a').click()
  await expect(page).toHaveURL(/\/shop$/)
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.locator('.product-card img:visible').first()).toHaveAttribute('src', /acoffee\.jpg/)

  const otherTab = await context.newPage()
  await otherTab.goto('/login')
  await expect(otherTab.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(otherTab.locator('.form-field input').first()).toHaveCSS('background-color', 'rgb(255, 250, 243)')
  await page.getByRole('button', { name: 'تغییر به تم تیره' }).click()
  await expect(otherTab.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(otherTab.locator('.form-field input').first()).toHaveCSS('background-color', 'rgb(27, 25, 23)')
  await otherTab.close()
  await page.goto('/')
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(21, 20, 19)')
  await expect(page.locator('.hero-visual img:visible')).toHaveAttribute('src', /acoffee-cinematic\.png/)
  await page.screenshot({ path: `artifacts/ui/theme-switch-dark-${testInfo.project.name}.png` })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('theme toggle works with keyboard when storage is unavailable on narrow screens', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 800 })
  await page.addInitScript(() => {
    Object.defineProperty(window, 'localStorage', { get() { throw new Error('Storage disabled') } })
  })
  await page.goto('/login')
  const toggle = page.getByRole('button', { name: 'تغییر به تم روشن' })
  await expect(toggle).toBeInViewport()
  await toggle.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.keyboard.press('Space')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
